{{--
  Template for the main navigation menu, styled for Bootstrap 5.
  This partial is intended to be included inside a Bootstrap navbar component.

  @var \Rendering\Domain\Contract\Partial\Navigation\NavigationLinkInterface[] $links An array of navigation link objects provided by the Navigation component.
--}}
<ul class="navbar-nav ms-auto mb-2 mb-lg-0">
    @foreach ($links as $link)
        <li class="nav-item">
            <a class="nav-link @if($link->isActive()) active @endif" 
                @if($link->isActive()) aria-current="page" @endif 
                href="{{ $link->url() }}">
                {{ $link->label() }}
            </a>
        </li>
    @endforeach
</ul>
